version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - node-service
    networks:
      - appnet

  node-service:
    build: ./backend/node-service
    ports:
      - "5000:5000"
    environment:
      - PYTHON_URL=http://python-service:8000
    depends_on:
      - python-service
    networks:
      - appnet

  python-service:
    build: ./backend/python-service
    ports:
      - "8000:8000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
